### PR TITLE
[BREAKCHANGE] Fix the issue of address in list_peers

### LINKED ISSUE #718: [list_peers] The addresses of the public node are displayed as []
list_peer:{"pubkey": "02b6d4e3ab86a2ca2fad6fae0ecb2e1e559e0b911939872a90abdda6d20302be71", "peer_id": "QmXen3eUHhywmutEzydCsW4hXBoeVmdET2FJvMX69XJ1Eo", "addresses": []}

graph_nodes: {"node_name": "CryptapeNode-1", "addresses": ["/ip4/18.162.235.225/tcp/8119/p2p/QmXen3eUHhywmutEzydCsW4hXBoeVmdET2FJvMX69XJ1Eo"]

expected : list_peer.addresses == graph_nodes.addresses

```
2025-05-28 10:42:00 [fiber_rpc.py:217][DEBUG] curl --location 'http://18.163.221.211:8227' --header 'Content-Type: application/json' --data '{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "list_peers",
    "params": []
}'
2025-05-28 10:42:00 [connectionpool.py:243][DEBUG] Starting new HTTP connection (1): 18.163.221.211:8227
2025-05-28 10:42:01 [connectionpool.py:546][DEBUG] http://18.163.221.211:8227 "POST / HTTP/11" 200 1287
2025-05-28 10:42:01 [fiber_rpc.py:227][DEBUG] response:
{"jsonrpc": "2.0", "result": {"peers": [{"pubkey": "02b6d4e3ab86a2ca2fad6fae0ecb2e1e559e0b911939872a90abdda6d20302be71", "peer_id": "QmXen3eUHhywmutEzydCsW4hXBoeVmdET2FJvMX69XJ1Eo", "addresses": []}, {"pubkey": "036c1588244f956d89b00aec36c4ea7da7990af5964f3d7d0a91e8c0a4342b893d", "peer_id": "QmapgHFsZ6k8mk9gzzSxZekYUbneicrnafwTZZbydbfSYe", "addresses": []}, {"pubkey": "0313dcf9cf18711b1b473a78ea56222dc44dcbfdf559d24dd937a0657d3bcb108f", "peer_id": "QmdyQWjPtbK4NWWsvy8s69NGJaQULwgeQDT5ZpNDrTNaeV", "addresses": ["/ip4/54.179.226.154/tcp/18228/p2p/QmdyQWjPtbK4NWWsvy8s69NGJaQULwgeQDT5ZpNDrTNaeV"]}, {"pubkey": "024714ca19abea4ddc0f3863ffdfb2e2cee76af87c477de4bc67c74a83f8140042", "peer_id": "Qmes1EBD4yNo9Ywkfe6eRw9tG1nVNGLDmMud1xJMsoYFKy", "addresses": ["/ip4/54.179.226.154/tcp/8228/p2p/Qmes1EBD4yNo9Ywkfe6eRw9tG1nVNGLDmMud1xJMsoYFKy"]}, {"pubkey": "03cbbbf3ec048b46949498bccb1e2a8e5c942cdab2f39c6d74916eced853bab71d", "peer_id": "QmTNTYkdrjRPy3Et7Xd8eofEN7WC7Vm49MCZUYXYXvpiN6", "addresses": []}, {"pubkey": "0221ab8a8faccd4d7a1190588830ac45398eeac57d73e6290494f722bd99997ea4", "peer_id": "QmdbU1YXxN9G7p3SAn4y8qBnGvisKU8ddh3ojEkWvuWEfW", "addresses": []}, {"pubkey": "0301f9f439e3490272acad7dbf9bd57fccfb1f780f9c6b0b90cc6f7447983d12fc", "peer_id": "QmSqSsbjkQG6aMBNEkG6hMLKQpMjLW3eaBmUdCghpRWqwJ", "addresses": []}]}, "id": 42}
2025-05-28 10:42:01 [fiber_rpc.py:217][DEBUG] curl --location 'http://18.163.221.211:8227' --header 'Content-Type: application/json' --data '{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "graph_nodes",
    "params": [
        {}
    ]
}'
2025-05-28 10:42:01 [connectionpool.py:243][DEBUG] Starting new HTTP connection (1): 18.163.221.211:8227
2025-05-28 10:42:01 [connectionpool.py:546][DEBUG] http://18.163.221.211:8227 "POST / HTTP/11" 200 26766
2025-05-28 10:42:01 [fiber_rpc.py:227][DEBUG] response:
{"jsonrpc": "2.0", "result": {"nodes": [{"node_name": "utxostack-hub-3", "addresses": ["/ip4/52.45.221.66/tcp/38228/p2p/QmdFwSVN75MEwrqtcMrTLAmnPB7sRzAYDWvtfFeqqtPG85"], "node_id": "03e7eb5bb09b3c97f64aad5aed5f77d7588fd8278a98f8e8dfc6ecf742856b15dd", "timestamp": "0x196331f76f3", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x989680", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SU7", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x2879ad494a8b755f744dbbdc0e3dae691f235762ce1cb06320438e4e44052212"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "utxostack-hub-4", "addresses": ["/ip4/52.45.221.66/tcp/48228/p2p/QmaR9YpMdjTrttgeB5Fgdzns4F9dQh9U5aCuht14MCGXyV"], "node_id": "02f2bd6c271a7072bbf63296cf3010f651812fd30a68f21615447c0a7f38f90385", "timestamp": "0x196332597fa", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x989680", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SU7", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x2879ad494a8b755f744dbbdc0e3dae691f235762ce1cb06320438e4e44052212"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "utxostack-hub-3", "addresses": ["/ip4/52.45.221.66/tcp/38228/p2p/QmRYF8DzQHwQpBazCfJBoNr9wLVGUg4FW2QRr44eHkUS5T"], "node_id": "020e634be4430f8765e75b94014f86dacd65827e44066c04cf8de8cc965b52914a", "timestamp": "0x196337ba4e2", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x989680", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SU7", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x2879ad494a8b755f744dbbdc0e3dae691f235762ce1cb06320438e4e44052212"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "utxostack-hub-4", "addresses": ["/ip4/52.45.221.66/tcp/48228/p2p/QmNwUqGPJQBnXUKPwaN6usX3hpW4R6fhsXZDZ4wqDP1A2a"], "node_id": "023a6a1868d31372aca892d082b41600dd38dd463a13e50140503c006a688efb38", "timestamp": "0x196337bca10", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x989680", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SU7", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x2879ad494a8b755f744dbbdc0e3dae691f235762ce1cb06320438e4e44052212"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "FTN20250416", "addresses": ["/ip4/52.45.221.66/tcp/50001/p2p/QmRn7zHWwFk9AeU2zLmc4TsaxJfeni1frLNPPYnZ9znxHp"], "node_id": "0379cabd44dadfe6e0db3471f01f80bd5e6976a26c0a98ada3ed02d360127c7a3a", "timestamp": "0x196c3767379", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0xa", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "bootnode2", "addresses": ["/ip4/54.179.226.154/tcp/18228/p2p/QmdyQWjPtbK4NWWsvy8s69NGJaQULwgeQDT5ZpNDrTNaeV"], "node_id": "0313dcf9cf18711b1b473a78ea56222dc44dcbfdf559d24dd937a0657d3bcb108f", "timestamp": "0x1971471bad6", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}]}, {"node_name": "cipher_fiber", "addresses": ["/ip4/121.7.67.162/tcp/8228/p2p/QmTNTYkdrjRPy3Et7Xd8eofEN7WC7Vm49MCZUYXYXvpiN6"], "node_id": "03cbbbf3ec048b46949498bccb1e2a8e5c942cdab2f39c6d74916eced853bab71d", "timestamp": "0x197147f8d33", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}]}, {"node_name": "", "addresses": ["/ip4/16.163.184.85/tcp/8229/p2p/QmR57vVw9iYMo1ZPQLjBJ2PeKKu2GAw61LN8QE5icEipMG"], "node_id": "039d7912a58612f600ef1cf9e9791f386187473a733f17f613b48e513e96eca3a2", "timestamp": "0x197148e1ac8", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}, {"cell_dep": {"out_point": {"tx_hash": "0x03d029480416c2fc927dfbfe0ed1916ffaf55d1e1f3146c55cf2d3dd5e674e61", "index": "0x0"}, "dep_type": "code"}}]}]}, {"node_name": "", "addresses": ["/ip4/16.163.184.85/tcp/8228/p2p/QmSqSsbjkQG6aMBNEkG6hMLKQpMjLW3eaBmUdCghpRWqwJ"], "node_id": "0301f9f439e3490272acad7dbf9bd57fccfb1f780f9c6b0b90cc6f7447983d12fc", "timestamp": "0x197148ee96d", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}, {"cell_dep": {"out_point": {"tx_hash": "0x03d029480416c2fc927dfbfe0ed1916ffaf55d1e1f3146c55cf2d3dd5e674e61", "index": "0x0"}, "dep_type": "code"}}]}]}, {"node_name": "FTN20250512", "addresses": ["/ip4/52.45.221.66/tcp/50001/p2p/QmcWUnFXVikZh4sz14N9P729j5m9k8PTNiUacNBxjLw6VH"], "node_id": "034877ff5f91793ded678a0113d10f88e1959e4223c92ce71756e210d2deddeb25", "timestamp": "0x1971492c880", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0xa", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "utxostack-hub-3", "addresses": ["/ip4/52.45.221.66/tcp/38228/p2p/QmUjVWuqF7r3sh88izUtta8y4LUc3FgsGPBLJMZ4Co9Nxa"], "node_id": "03d2e665eb55bfb7c92dd99413293647a1cd100b8585a2c5b051dd7bed40c33994", "timestamp": "0x19714935b5a", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x989680", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SU7", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x2879ad494a8b755f744dbbdc0e3dae691f235762ce1cb06320438e4e44052212"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "utxostack-hub-2", "addresses": ["/ip4/52.45.221.66/tcp/28228/p2p/QmdbU1YXxN9G7p3SAn4y8qBnGvisKU8ddh3ojEkWvuWEfW"], "node_id": "0221ab8a8faccd4d7a1190588830ac45398eeac57d73e6290494f722bd99997ea4", "timestamp": "0x1971493a28d", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x989680", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SU7", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x2879ad494a8b755f744dbbdc0e3dae691f235762ce1cb06320438e4e44052212"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "utxostack-hub-4", "addresses": ["/ip4/52.45.221.66/tcp/48228/p2p/QmYRNjy1sZVYiVotFBZUvvth9JH2kyNAabK2KBGYLFkhkD"], "node_id": "03cce3c4313d20577bf117901ddeb921fc51c69c1c41cfa16c3368202266f94e59", "timestamp": "0x1971494afdf", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x989680", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SU7", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x2879ad494a8b755f744dbbdc0e3dae691f235762ce1cb06320438e4e44052212"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}, {"node_name": "bootnode1", "addresses": ["/ip4/54.179.226.154/tcp/8228/p2p/Qmes1EBD4yNo9Ywkfe6eRw9tG1nVNGLDmMud1xJMsoYFKy"], "node_id": "024714ca19abea4ddc0f3863ffdfb2e2cee76af87c477de4bc67c74a83f8140042", "timestamp": "0x19714a88421", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}]}, {"node_name": "CryptapeNode-2", "addresses": ["/ip4/18.163.221.211/tcp/8119/p2p/QmbKyzq9qUmymW2Gi8Zq7kKVpPiNA1XUJ6uMvsUC4F3p89"], "node_id": "0291a6576bd5a94bd74b27080a48340875338fff9f6d6361fe6b8db8d0d1912fcc", "timestamp": "0x19714a99ce6", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0xa32aef600", "udt_cfg_infos": [{"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x77359400", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}]}, {"node_name": "CryptapeNode-1", "addresses": ["/ip4/18.162.235.225/tcp/8119/p2p/QmXen3eUHhywmutEzydCsW4hXBoeVmdET2FJvMX69XJ1Eo"], "node_id": "02b6d4e3ab86a2ca2fad6fae0ecb2e1e559e0b911939872a90abdda6d20302be71", "timestamp": "0x19714a9d452", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0xa32aef600", "udt_cfg_infos": [{"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x77359400", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}]}, {"node_name": "utxostack-hub-1", "addresses": ["/ip4/52.45.221.66/tcp/18228/p2p/QmapgHFsZ6k8mk9gzzSxZekYUbneicrnafwTZZbydbfSYe"], "node_id": "036c1588244f956d89b00aec36c4ea7da7990af5964f3d7d0a91e8c0a4342b893d", "timestamp": "0x19714bf2896", "chain_hash": "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606", "auto_accept_min_ckb_funding_amount": "0x2540be400", "udt_cfg_infos": [{"name": "USDI", "script": {"code_hash": "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037", "hash_type": "type", "args": "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"}, "auto_accept_amount": "0x989680", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b"}}]}, {"name": "RUSD", "script": {"code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a", "hash_type": "type", "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f"}}]}, {"name": "SU7", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x2879ad494a8b755f744dbbdc0e3dae691f235762ce1cb06320438e4e44052212"}, "auto_accept_amount": "0x3b9aca00", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}, {"name": "SEAL", "script": {"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb", "hash_type": "type", "args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"}, "auto_accept_amount": "0x9184e72a000", "cell_deps": [{"type_id": {"code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type", "args": "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"}}]}]}], "last_cursor": "0x0000019714bf289602036c1588244f956d89b00aec36c4ea7da7990af5964f3d7d0a91e8c0a4342b893d000000"}, "id": 42}

```

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #718

### CODE REVIEW

File: crates/fiber-lib/src/fiber/network.rs [hunk 1]
```diff
@@ -2966,10 +2981,11 @@ where
         let store = self.store.clone();
         self.peer_session_map
             .insert(remote_peer_id.clone(), (session.id, session.ty));
-        if self
-            .state_to_be_persisted
-            .save_peer_pubkey(remote_peer_id.clone(), remote_pubkey)
```
Comment (chenyukang) [inline crates/fiber-lib/src/fiber/network.rs:2971]: @quake is there any specific reason we didn't store `session.address` here for remote peers?

File: crates/fiber-lib/src/fiber/network.rs [hunk 2]
```diff
@@ -203,8 +203,10 @@ pub struct PeerInfo {
     #[serde_as(as = "DisplayFromStr")]
     pub peer_id: PeerId,
 
-    /// A list of multi-addresses associated with the peer.
-    pub addresses: Vec<MultiAddr>,
+    /// The multi-address associated with the connecting peer.
+    /// Note: this is only the address which used for connecting to the peer, not all addresses of the peer.
+    /// The `graph_nodes` in Graph rpc module will return all addresses of the peer.
```
Comment (chenyukang) [inline crates/fiber-lib/src/fiber/network.rs:208]: @quake @gpBlockchain 
this is a broken change since I renamed this field.

**Review by quake — APPROVED** [review]
