### PR TITLE
fix: resolve shutdown script size bug

### LINKED ISSUE #332: [shutdown_channel] panic when close_script too long
```
curl --location 'http://127.0.0.1:8228' --header 'Content-Type: application/json' --data '{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "shutdown_channel",
    "params": [
        {
            "channel_id": "0x7f21730a5f83fd8994865f0fa70ca1e47f4596dab030311f1ee935587e497675",
            "close_script": {
                "code_hash": "0x1bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                "hash_type": "type",
                "args": "0x926330b31f3adf5433a31debae103279ac204b199fda531f81c1e9f8cc7027608f59de42d42fccdd56b45731b4ee62f404b7e725c7eb14a69b7367a923dc1d67b5a498380dcca88c628859085b3836ee0b5240f69ca12b2ca2417a4deec3cc8b7ba239aafe3824630d37fd9d2197d9024e075c2a22634354fe7d55b8c3ee1a26d662cb87fe476b7d142c37fb0606e64fee07bee6ba3d113eac7d7b4fb97a56bf71d08a5edeb0f9e00803447f804af9a5bd96d012fbaaa867b5ad43fde5778847a531dd90768fc310a558cc52190eeba78f939c3aad5463115fc777a5f7c434b25554e4db368bcfe7be64e8f0fcddc4da295bc94d93752370b7f85dfd415d5ccaf1573ff52fae9b5414982b641fcbe62cb181a6c738f239f43edbb05774baa64484a8aeeab942e7f84039c55685ee5591126596ea423858c9ba98f1284b8fd0c89cad6d8db88fc1408b8f11145ed4eeef172cf78296b352b939879c859e594dde5f4584799f95ae22cd923edc9ad65832e6709d2fb3381daafd0251c67897d7f65abd374df4e826bfcc7d5d9e137afdd255bd4b81b15f91d01a92dde0ff1dd7cbff373429b4f012b74d3ae319bb2dd7d62b643900e3f01ef0bc2b2b707e9657d41b695d76c9ad9f11074e16a1c085b5c5b94521d11e8581fdd815363f6068e9b9a31cd672eeefbf8d69fd39cb1c0be405e0f1eee2"
            },
            "fee_rate": "0x3FC"
        }
    ]
}'
```
return panic
```
thread 'tokio-runtime-worker' panicked at src/fiber/channel.rs:4207:17:
assertion `left == right` failed
  left: 558
 right: 528
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

[node.log](https://github.com/user-attachments/files/17842406/node.log)

### PR DESCRIPTION
**Pull request by quake**
resolve #332 and #274

### CODE REVIEW

**Review by chenyukang — APPROVED** [review]

File: src/fiber/config.rs [hunk 1]
```diff
@@ -113,12 +103,12 @@ pub struct FiberConfig {
     #[arg(name = "FIBER_SCRIPTS", long = "fiber-scripts", env, value_parser, num_args = 0.., value_delimiter = ',')]
     pub scripts: Vec<FiberScript>,
 
-    /// minimum ckb funding amount for auto accepting an open channel requests, aunit: shannons [default: 16200000000 shannons]
+    /// minimum ckb funding amount for auto accepting an open channel requests, aunit: shannons [default: 10000000000 shannons]
     #[arg(
```
Comment (chenyukang) [inline src/fiber/config.rs:107]: `aunit` -> `unit`.

**Comment by chenyukang** [comment]
I think we should add more document for `open_channel` about the funding limits and conditions.

at here:
https://github.com/nervosnetwork/fiber/blob/afe2219e6f9ac9d19c704ef3db9a9b105cd2f24f/src/rpc/channel.rs#L320

**Comment by quake** [comment]
> I think we should add more document for `open_channel` about the funding limits and conditions.
> 
> at here:
> 
> https://github.com/nervosnetwork/fiber/blob/afe2219e6f9ac9d19c704ef3db9a9b105cd2f24f/src/rpc/channel.rs#L320

I will add more detail after complete #337
