### PR TITLE
Fix payself bug with mixed channels of UDT 

### LINKED ISSUE #678: [send_payment]: The allow_self_payment parameter affects unrelated XUDT channels
version: 0.5.0
network: testnet

After repeated testing, sending CKB with the allow_self_payment parameter causes the Seal channel balance to change.No anomalies occur when the parameter is not included.Additionally, sending USDI affects the RUSD channel.

Image

### create invoce
```
{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "new_invoice",
    "params": [
        {
            "amount": "0xba43b7400",
            "currency": "Fibt",
            "description": "node",
            "expiry": "0x2581",
            "final_cltv": "0x28",
            "payment_preimage": "0xc11111111111111111111111bb164b1b1141f011aefec11e1111111111111111",
            "hash_algorithm": "sha256"
        }
    ]
}
```

### send_payment
```
echo '{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "send_payment",
    "params": [
        {
          "invoice": "fibt500000000001p49t2j4c5ujgfw0pnm6vkhwhejnk05jkgxmqq09qwnuhtfnk2e5yk8v26t4j7n37ysp4ztrgfhvar0ufe8up58t052s677d0z69nec4tzs7jpegpj0mzerxzk0smfxcfmauaxc56ram3p5c0y93f80wy37svrwzrrlj3fm888u8txur4f5hqmc4c8xwe3m3uuf8xaq037fjhrp260mgunqpawyjev3fjwqr6deg98zy66zzmgra2rytl0mqverpxva8g6chyy4uuyjv32e8hd7jwn2vgs6jwgw4377sks3q8zazjqm0n50jnxxr9qql7yfrd",
          "allow_self_payment": true
        }
    ]
}' \
| curl -H 'content-type: application/json' -d @- \
http://127.0.0.1:8227
```

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #678

Refactor test utilities to support creating UDT channels in unit tests.

### CODE REVIEW

**Comment by gpBlockchain** [comment]
lgtm

File: src/fiber/graph.rs [hunk 1]
```diff
@@ -680,6 +679,25 @@ where
         self.channels.get(outpoint)
     }
 
+    pub fn get_outbound_channel_info_and_update(
```
Comment (quake) [inline src/fiber/graph.rs]: suggest to remove `pub`

File: src/fiber/graph.rs [hunk 2]
```diff
@@ -1054,58 +1071,59 @@ where
...
-                } = hint;
+                // hop hint only referring to private channels for sender node,
+                // if we get public channel information for this hophint, we just ignore this hophint
+                if let (Some(channel_info), Some(channel_update)) =
+                    self.get_outbound_channel_info_and_update(&hint.channel_outpoint, hint.pubkey)
+                {
+                    if channel_info.udt_type_script != udt_type_script || channel_update.enabled {
+                        continue;
+                    }
+                }
```
Comment (quake) [inline src/fiber/graph.rs]: suggest to use `hop_hints.retain(...)` to filter out public channel first then loop the hints.

File: src/fiber/graph.rs [hunk 3]
```diff
@@ -1250,54 +1249,60 @@ where
...
+                )
             })
-            .collect();
-        for (from, _, channel_info, channel_update) in self.get_node_inbounds(node) {
-            if let Some(balance) = channel_update.outbound_liquidity {
-                if balance < amount {
-                    continue;
+            .filter(|(_, _, expiry, _, channel_info, channel_update)| {
+                // we also check the validity of hint, if the hint is not valid, we will skip it
+                // for instance, if user specify a hint channel with UDT, but the payment is not UDT,
```
Comment (quake) [inline src/fiber/graph.rs]: Is this code comment outdated, because we have removed the hop_hints param from `adjust_target_for_route_self` now, and does not need to mention hint in the comment?

File: src/fiber/graph.rs (hunk 2 above)
Comment (chenyukang) [reply src/fiber/graph.rs]: `hop_hints` is not mutable, if we want to use `retain` we need to change the function signature or use a `clone` for `hop_hints`.

I think we should not require mutable here, I changed the parameter from `hop_hints: Vec<HopHint>`  to `hop_hints: &[HopHint]`, so we don't need to clone it when call `find_path`.

Comment (quake) [reply src/fiber/graph.rs]: I see, then we may use filter first:
```rust
            let filtered_hints = hop_hints.iter().filter(|hint|
                match self.get_outbound_channel_info_and_update(&hint.channel_outpoint, hint.pubkey) {
                    (Some(channel_info), Some(channel_update)) => {
                        channel_info.udt_type_script == udt_type_script && !channel_update.enabled
                    },
                    _ => true,
                }
            );
            for hint in filtered_hints {
             }
```

**Review by quake — APPROVED** [review]
