### PR TITLE
Derive secrets from commitment points

### LINKED ISSUE #63: Actually derive new secrets for each commitment transaction
Currently we didn't actually use the per commitment point to derive new secret keys.

https://github.com/contrun/ckb-pcn-node/blob/7de2f8ce969da5ca6cdc7a59c8ca16ac296b8db6/src/ckb/channel.rs#L3191-L3195

Besides the obvious security implication, it may make some bugs go unnoticed. For example, one bug in https://github.com/contrun/ckb-pcn-node/pull/62 should be discovered much earlier if we are actually using different keys for different commitment transaction.

> The second bug is that we are using the wrong per commitment point to construct commitment transaction. We should use the current commitment number (and obtain the current commitment point) to construct commitment transaction. Previously, we used previous commitment number. This bug goes undiscovered because we didn't actually use commitment point to derive new public keys. We just copy the old keys. Thus commitment transaction are still the same for both parties.

### PR DESCRIPTION
**Pull request by contrun**
Fixes #63

### CODE REVIEW

File: src/ckb/types.rs [hunk 1]
```diff
@@ -285,6 +297,14 @@ impl Privkey {
     pub fn pubkey(&self) -> Pubkey {
         Pubkey::from(self.0.public_key(secp256k1_instance()))
     }
+
+    pub fn tweak<I: Into<[u8; 32]>>(&self, scalar: I) -> Self {
```
Comment (doitian) [inline src/ckb/types.rs:301]: Since you only need ref of `[u8; 32]`, `AsRef` is better than `Into` here.

File: src/ckb/channel.rs [hunk 2]
```diff
@@ -504,10 +509,6 @@ impl<S> ChannelActor<S> {
         match flags {
             CommitmentSignedFlags::SigningCommitment(flags) => {
                 let flags = flags | SigningCommitmentFlags::OUR_COMMITMENT_SIGNED_SENT;
-                // Normally commitment number will be incremented after received a RevokeAndAck message.
-                // But here channel has not been etablished yet, so we will not receive RevokeAndAck message.
-                // We increment the commitment number here instead.
-                state.increment_local_commitment_number();
```
Comment (doitian) [inline src/ckb/channel.rs:510]: Could you explain why this is no longer needed?

File: src/ckb/channel.rs [hunk 3]
```diff
@@ -2698,14 +2705,14 @@ impl ChannelActorState {
...
+            self.get_remote_nonce(),
+            &commitment_signed.next_local_nonce
+        );
         self.remote_nonce = Some(commitment_signed.next_local_nonce);
         match flags {
             CommitmentSignedFlags::SigningCommitment(flags) => {
-                // Normally commitment number will be incremented after sent a RevokeAndAck message.
-                // But here channel has not been etablished yet, so we will not send RevokeAndAck message.
-                // We increment the commitment number here instead.
-                self.increment_remote_commitment_number();
```
Comment (doitian) [inline src/ckb/channel.rs:2719]: Could you explain why this is no longer needed?

**Review by doitian — COMMENTED** [review]
Skimmed

File: src/ckb/channel.rs (hunk 2 above)
Comment (contrun) [reply src/ckb/channel.rs:510]: This commit has relevant information about this change. https://github.com/nervosnetwork/cfn-node/pull/96/commits/11f710bafc809af779441daf1eb73b1b603e185c. TLDR is that I moved the code to `on_channel_ready` function. It has to be delayed to there because incrementing these numbers too soon may cause problems.

File: src/ckb/channel.rs (hunk 3 above)
Comment (contrun) [reply src/ckb/channel.rs:2719]: Ditto

File: src/ckb/types.rs (hunk 1 above)
Comment (contrun) [reply src/ckb/types.rs:301]: The problem I encountered is that https://doc.rust-lang.org/std/convert/trait.AsRef.html#tymethod.as_ref `AsRef<[u8; 32]>` is not automatically implemented for `[u8; 32]`. The automatic implementation of the rust compiler only works without the length 32. https://doc.rust-lang.org/std/convert/trait.AsRef.html#impl-AsRef%3C%5BT%5D%3E-for-%5BT%5D
