### PR TITLE
Fix Musig2RoundFinalizeError caused by concurrency problem 

### LINKED ISSUE #475: [send_payment] return Musig2VerifyError when multiple nodes send payment self
commit: bde0dbc

multiple nodes keep transferring to themselves, which causes the node to report TlcAmountExceedLimit, Musig2RoundFinalizeError, and then causes the node get stuck in the Waitingtlcack

image

err log
```
  2025-01-14T09:03:51.930022Z ERROR fnn::fiber::channel: Error while processing channel command: TlcAmountExceedLimit

  2025-01-14T09:02:10.483359Z ERROR fnn::fiber::channel: Error while processing channel command: WaitingTlcAck
  2025-01-14T09:02:10.538608Z ERROR fnn::fiber::channel: Error while processing channel command: WaitingTlcAck
  2025-01-14T09:02:13.812686Z ERROR fnn::fiber::channel: Error while processing channel command: WaitingTlcAck
  2025-01-14T09:02:31.744385Z ERROR fnn::fiber::channel: Error while processing channel message: Musig2RoundFinalizeError(InvalidAggregatedSignature(BadSignature)) with message: RevokeAndAck(RevokeAndAck { channel_id: Hash256(0x89a8477ab5e44def0f51c2a4f6f56f400ca2b78817f44c78ac63b4a2cd0067e3), revocation_partial_signature: Valid(Scalar(#244ee3579f80afe1)), commitment_tx_partial_signature: Valid(Scalar(#3f7b65e4e9b6c1a1)), next_per_commitment_point: Pubkey(PublicKey(2df118cb974463253048933b8d210087608006e35eca2fbf59ad0ccd3679a7ed9f6079a3a860d5abcc641335f0dbd4fe9167e8a2fdbb8e31607320739e627d8b)) })
  2025-01-14T09:02:34.156586Z ERROR fnn::fiber::channel: Error while processing channel message: Musig2VerifyError(BadSignature) with message: CommitmentSigned(CommitmentSigned { channel_id: Hash256(0x89a8477ab5e44def0f51c2a4f6f56f400ca2b78817f44c78ac63b4a2cd0067e3), funding_tx_partial_signature: Valid(Scalar(#60d4c10d4aff75b1)), commitment_tx_partial_signature: Valid(Scalar(#7e60d2f31774138b)), next_local_nonce: PubNonce { R1: Point(027bfe430069be22b9c88cae534fd9b84b9cb84e241d2278ca74ffc73eefd90b7d), R2: Point(03a1ba7ec87558c2a2a0b219fb5d53793cb588ced9c7a4d39a8e6fdb68efe8328f) } })
```

### LINKED ISSUE #480: [send_payment] return Musig2RoundFinalizeError when mid node update_channel
commit :bde0dbc
1. open_channel(node1,node2)
2. open_channel(node2,node3)
3. open_channel(node3,node4)
4. for i in range(50):
           node1.send_payment(node4)
5. update_channel(node3)
6. node1.send_payment(node4)-> WaitingTlcAck

node1.log:
[node.log](https://github.com/user-attachments/files/18409352/node.log)
```
  2025-01-14T10:47:26.952666Z ERROR fnn::fiber::channel: Error while processing channel command: WaitingTlcAck

```
node2.log: 
[node.log](https://github.com/user-attachments/files/18409362/node.log)
```
  2025-01-14T10:47:33.743610Z ERROR fnn::fiber::channel: Error while processing channel message: Musig2RoundFinalizeError(InvalidAggregatedSignature(BadSignature)) with message: RevokeAndAck(RevokeAndAck { channel_id: Hash256(0x9820baa904d5e8380d93bb5776b626a49885d2e43c7e7829fbddff017599713b), revocation_partial_signature: Valid(Scalar(#447610991cd281d7)), commitment_tx_partial_signature: Valid(Scalar(#bb7c25951bbf544a)), next_per_commitment_point: Pubkey(PublicKey(efc1230a146d02c53e0e94ee36c50a985558c7e4fefbfaa158e86d0dd7d8f6d913d2057e84f6c7a4d05eeba2371964fa33c98fa6f9cb2f28ac263baf0827ac0f)) })
  2025-01-14T10:47:34.090827Z ERROR fnn::fiber::channel: Error while processing channel message: Musig2VerifyError(BadSignature) with message: CommitmentSigned(CommitmentSigned { channel_id: Hash256(0x9820baa904d5e8380d93bb5776b626a49885d2e43c7e7829fbddff017599713b), funding_tx_partial_signature: Valid(Scalar(#7b090f9f79cf6856)), commitment_tx_partial_signature: Valid(Scalar(#efc8e93cd87b1d3d)), next_local_nonce: PubNonce { R1: Point(0201cf991bc4bc704b4d92ddbd9335b8d653dc517ec2b84cf2bfb2d20383a4b8c5), R2: Point(031085f4c1794d6cba9c3a708b58db897415a10350c116424790477af86fb9c9cd) } })
```

node3.log:[node.log](https://github.com/user-attachments/files/18409371/node.log)

```

  2025-01-14T10:46:47.183297Z ERROR fnn::fiber::channel: Error while processing channel command: WaitingTlcAck
  2025-01-14T10:46:47.518864Z ERROR fnn::fiber::channel: Error while processing channel command: WaitingTlcAck
  2025-01-14T10:46:48.192225Z ERROR fnn::fiber::channel: Error while processing channel command: WaitingTlcAck
  2025-01-14T10:47:02.894486Z ERROR fnn::fiber::channel: too low forward_fee: 100000, expected_fee: Ok(1000000)
```

node4.log : 
[node.log](https://github.com/user-attachments/files/18409379/node.log)

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #480
Fixes #475

When there are multiple `RemoveTlcFail` happened at the same time, node `A`'s TLC with `RemoveTlcFail` may in [RemoveWaitAck](https://github.com/nervosnetwork/fiber/blob/6f19693034c8a27db226959685111cc5111f90f9/src/fiber/channel.rs#L6671), node `B`'s corresponding TLC may already be removed from memory, so Musig2RoundFinalizeError will be triggered.

In this PR, we keep `RemoveTlcFail` in TLC list and will remove it when the number exceeds 2 in any direction of the channel.

### CODE REVIEW

File: src/fiber/channel.rs [hunk 1]
```diff
@@ -2516,6 +2546,7 @@ pub struct TlcInfo {
     ///                ^^^^                 ^^^^
     ///
     pub previous_tlc: Option<(Hash256, TLCId)>,
+    pub removed_confirmed_at: Option<u64>,
```
Comment (contrun) [inline src/fiber/channel.rs:2551]: With this newer field added, we need to migrate state.

File: src/fiber/channel.rs [hunk 2]
```diff
@@ -4638,6 +4696,31 @@ impl ChannelActorState {
...
+                        tlc.status,
+                        TlcStatus::Inbound(InboundTlcStatus::RemoveAckConfirmed)
+                            | TlcStatus::Outbound(OutboundTlcStatus::RemoveAckConfirmed)
+                            | TlcStatus::Outbound(OutboundTlcStatus::RemoveWaitAck)
+                    )
+            })
+            .map(|tlc| (tlc.tlc_id, tlc.removed_confirmed_at.unwrap_or(u64::MAX)))
+            .collect();
+
+        if failed_tlcs.len() >= 3 {
```
Comment (contrun) [inline src/fiber/channel.rs]: Have you tried to apply all failed tlcs here? Since we are only removing one failed tlc for one time, I am afraid that this approach may only be hiding the problem appeared in the unit tests, it can still show up in some rare situation in the future.

File: src/fiber/tests/test_utils.rs [hunk 3]
```diff
@@ -840,6 +864,44 @@ impl NetworkNode {
...
+        let default_unexpected_events = vec![
+            "Musig2VerifyError",
+            "Musig2RoundFinalizeError",
+            "InvalidOnionError",
+        ];
+        for event in default_unexpected_events {
+            unexpected_events.insert(event.to_string());
+        }
+
+        let unexpected_events = Arc::new(TokioRwLock::new(unexpected_events));
```
Comment (contrun) [inline src/fiber/tests/test_utils.rs:880]: I think using [OutputPort in ractor::port::output - Rust](https://docs.rs/ractor/latest/ractor/port/output/struct.OutputPort.html) and [OutputPortSubscriber in ractor::port::output - Rust](https://docs.rs/ractor/latest/ractor/port/output/type.OutputPortSubscriber.html) for current  `event_receiver/event_sender` would be better, because `OutputPort`/`OutputPortSubscriber` natively supports broadcasting (send events to multiple subscribers) and filtering out uninterested events (creating a subscriber to subscribe only unexpected events is easy). Of course, using `OutputPort`/`OutputPortSubscriber` instead of `mpsc::Sender<NetworkServiceEvent>/mpsc::Receiver<NetworkServiceEvent>` requires much more work.

File: src/fiber/channel.rs [hunk 4]
```diff
@@ -2691,6 +2738,7 @@ pub struct TlcState {
     pub received_tlcs: PendingTlcs,
     pub retryable_tlc_operations: Vec<RetryableTlcOperation>,
     pub applied_add_tlcs: HashSet<TLCId>,
+    pub applied_remove_tlcs: HashSet<TLCId>,
```
Comment (contrun) [inline src/fiber/channel.rs:2764]: We need a migration for this new field.

File: src/fiber/channel.rs [hunk 5]
```diff
@@ -1098,6 +1117,10 @@ where
         tlc_id: TLCId,
     ) -> Result<(), ProcessingChannelError> {
         let channel_id = state.get_id();
+        if state.tlc_state.applied_remove_tlcs.contains(&tlc_id) {
+            return Ok(());
+        }
+        state.tlc_state.applied_remove_tlcs.insert(tlc_id);
```
Comment (quake) [inline src/fiber/channel.rs]:
```suggestion
        if !state.tlc_state.applied_remove_tlcs.insert(tlc_id) {
            return Ok(());
        }
```

File: src/fiber/channel.rs [hunk 6]
```diff
@@ -2683,6 +2730,34 @@ impl PendingTlcs {
...
+                        TlcStatus::Inbound(InboundTlcStatus::RemoveAckConfirmed)
+                            | TlcStatus::Outbound(OutboundTlcStatus::RemoveAckConfirmed)
+                            | TlcStatus::Outbound(OutboundTlcStatus::RemoveWaitAck)
+                    )
+            })
+            .map(|tlc| (tlc.tlc_id, tlc.removed_confirmed_at.unwrap_or(u64::MAX)))
+            .collect::<Vec<_>>();
+
+        let keep_failed_num = 2;
+        if failed_tlcs.len() >= keep_failed_num {
```
Comment (quake) [inline src/fiber/channel.rs]: I think it should be `failed_tlcs.len() > keep_failed_num`

File: src/fiber/channel.rs [hunk 7]
```diff
@@ -2683,6 +2730,34 @@ impl PendingTlcs {
             .cloned()
             .collect()
     }
+
+    pub fn get_oldest_failed_tlcs(&self) -> Vec<TLCId> {
+        let mut failed_tlcs = self
+            .tlcs
+            .iter()
+            .filter(|tlc| {
```
Comment (quake) [inline src/fiber/channel.rs]: can we use `filter_map` to return the tlc which is `is_fail_remove_confirmed` only?

File: src/fiber/history.rs [hunk 8]
```diff
@@ -254,7 +257,15 @@ impl InternalResult {
                 TlcErrorCode::PermanentChannelFailure => {
                     self.fail_pair(nodes, index + 1);
                 }
-                TlcErrorCode::FeeInsufficient | TlcErrorCode::IncorrectTlcExpiry => {
+                TlcErrorCode::FeeInsufficient => {
+                    need_to_retry = true;
+                    eprintln!("need_to_retry: {:?}, index: {:?}", need_to_retry, index);
```
Comment (quake) [inline src/fiber/history.rs]: please remove eprintln

File: src/fiber/channel.rs (hunk 1 above)
Comment (chenyukang) [reply src/fiber/channel.rs:2551]: yes, I will add migration if all the code changes is OK.

File: src/fiber/channel.rs (hunk 2 above)
Comment (chenyukang) [reply src/fiber/channel.rs]: We can not apply all the failed tlcs, because the timing of a TLC change to `RemoveAckConfirmed` is different for two endpoint, this is the root cause of verifying signature error.

File: src/fiber/channel.rs (hunk 6 above)
Comment (chenyukang) [reply src/fiber/channel.rs]: `failed_tlcs.len() > keep_failed_num` means we keep 2 confirmed failed tlcs, the minimal safe way is we only keep another extra confirmed failed tlc.

I think both are OK, I changed as you suggested which may sound safer.

File: src/fiber/channel.rs (hunk 4 above)
Comment (chenyukang) [reply src/fiber/channel.rs:2764]: added: https://github.com/nervosnetwork/fiber/pull/493/commits/d8d420d2f680adbee13579d8f5fdfa7bec7427ec

**Comment by gpBlockchain** [comment]
LGTM

**Review by quake — APPROVED** [review]
